// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: events.proto

package events

import (
	types "github.com/getAlby/hub/lnclient/ldk-server/grpc/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChannelState int32

const (
	ChannelState_CHANNEL_STATE_UNSPECIFIED ChannelState = 0
	ChannelState_CHANNEL_STATE_PENDING     ChannelState = 1
	ChannelState_CHANNEL_STATE_READY       ChannelState = 2
	ChannelState_CHANNEL_STATE_OPEN_FAILED ChannelState = 3
	ChannelState_CHANNEL_STATE_CLOSED      ChannelState = 4
)

// Enum value maps for ChannelState.
var (
	ChannelState_name = map[int32]string{
		0: "CHANNEL_STATE_UNSPECIFIED",
		1: "CHANNEL_STATE_PENDING",
		2: "CHANNEL_STATE_READY",
		3: "CHANNEL_STATE_OPEN_FAILED",
		4: "CHANNEL_STATE_CLOSED",
	}
	ChannelState_value = map[string]int32{
		"CHANNEL_STATE_UNSPECIFIED": 0,
		"CHANNEL_STATE_PENDING":     1,
		"CHANNEL_STATE_READY":       2,
		"CHANNEL_STATE_OPEN_FAILED": 3,
		"CHANNEL_STATE_CLOSED":      4,
	}
)

func (x ChannelState) Enum() *ChannelState {
	p := new(ChannelState)
	*p = x
	return p
}

func (x ChannelState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChannelState) Descriptor() protoreflect.EnumDescriptor {
	return file_events_proto_enumTypes[0].Descriptor()
}

func (ChannelState) Type() protoreflect.EnumType {
	return &file_events_proto_enumTypes[0]
}

func (x ChannelState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChannelState.Descriptor instead.
func (ChannelState) EnumDescriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{0}
}

type ChannelClosureInitiator int32

const (
	ChannelClosureInitiator_CHANNEL_CLOSURE_INITIATOR_UNSPECIFIED ChannelClosureInitiator = 0
	ChannelClosureInitiator_CHANNEL_CLOSURE_INITIATOR_LOCAL       ChannelClosureInitiator = 1
	ChannelClosureInitiator_CHANNEL_CLOSURE_INITIATOR_REMOTE      ChannelClosureInitiator = 2
	ChannelClosureInitiator_CHANNEL_CLOSURE_INITIATOR_UNKNOWN     ChannelClosureInitiator = 3
)

// Enum value maps for ChannelClosureInitiator.
var (
	ChannelClosureInitiator_name = map[int32]string{
		0: "CHANNEL_CLOSURE_INITIATOR_UNSPECIFIED",
		1: "CHANNEL_CLOSURE_INITIATOR_LOCAL",
		2: "CHANNEL_CLOSURE_INITIATOR_REMOTE",
		3: "CHANNEL_CLOSURE_INITIATOR_UNKNOWN",
	}
	ChannelClosureInitiator_value = map[string]int32{
		"CHANNEL_CLOSURE_INITIATOR_UNSPECIFIED": 0,
		"CHANNEL_CLOSURE_INITIATOR_LOCAL":       1,
		"CHANNEL_CLOSURE_INITIATOR_REMOTE":      2,
		"CHANNEL_CLOSURE_INITIATOR_UNKNOWN":     3,
	}
)

func (x ChannelClosureInitiator) Enum() *ChannelClosureInitiator {
	p := new(ChannelClosureInitiator)
	*p = x
	return p
}

func (x ChannelClosureInitiator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChannelClosureInitiator) Descriptor() protoreflect.EnumDescriptor {
	return file_events_proto_enumTypes[1].Descriptor()
}

func (ChannelClosureInitiator) Type() protoreflect.EnumType {
	return &file_events_proto_enumTypes[1]
}

func (x ChannelClosureInitiator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChannelClosureInitiator.Descriptor instead.
func (ChannelClosureInitiator) EnumDescriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{1}
}

type ChannelStateChangeReasonKind int32

const (
	ChannelStateChangeReasonKind_CHANNEL_STATE_CHANGE_REASON_KIND_UNSPECIFIED                                ChannelStateChangeReasonKind = 0
	ChannelStateChangeReasonKind_CHANNEL_STATE_CHANGE_REASON_KIND_COUNTERPARTY_FORCE_CLOSED                  ChannelStateChangeReasonKind = 1
	ChannelStateChangeReasonKind_CHANNEL_STATE_CHANGE_REASON_KIND_HOLDER_FORCE_CLOSED                        ChannelStateChangeReasonKind = 2
	ChannelStateChangeReasonKind_CHANNEL_STATE_CHANGE_REASON_KIND_LEGACY_COOPERATIVE_CLOSURE                 ChannelStateChangeReasonKind = 3
	ChannelStateChangeReasonKind_CHANNEL_STATE_CHANGE_REASON_KIND_COUNTERPARTY_INITIATED_COOPERATIVE_CLOSURE ChannelStateChangeReasonKind = 4
	ChannelStateChangeReasonKind_CHANNEL_STATE_CHANGE_REASON_KIND_LOCALLY_INITIATED_COOPERATIVE_CLOSURE      ChannelStateChangeReasonKind = 5
	ChannelStateChangeReasonKind_CHANNEL_STATE_CHANGE_REASON_KIND_COMMITMENT_TX_CONFIRMED                    ChannelStateChangeReasonKind = 6
	ChannelStateChangeReasonKind_CHANNEL_STATE_CHANGE_REASON_KIND_FUNDING_TIMED_OUT                          ChannelStateChangeReasonKind = 7
	ChannelStateChangeReasonKind_CHANNEL_STATE_CHANGE_REASON_KIND_PROCESSING_ERROR                           ChannelStateChangeReasonKind = 8
	ChannelStateChangeReasonKind_CHANNEL_STATE_CHANGE_REASON_KIND_DISCONNECTED_PEER                          ChannelStateChangeReasonKind = 9
	ChannelStateChangeReasonKind_CHANNEL_STATE_CHANGE_REASON_KIND_OUTDATED_CHANNEL_MANAGER                   ChannelStateChangeReasonKind = 10
	ChannelStateChangeReasonKind_CHANNEL_STATE_CHANGE_REASON_KIND_COUNTERPARTY_COOP_CLOSED_UNFUNDED_CHANNEL  ChannelStateChangeReasonKind = 11
	ChannelStateChangeReasonKind_CHANNEL_STATE_CHANGE_REASON_KIND_LOCALLY_COOP_CLOSED_UNFUNDED_CHANNEL       ChannelStateChangeReasonKind = 12
	ChannelStateChangeReasonKind_CHANNEL_STATE_CHANGE_REASON_KIND_FUNDING_BATCH_CLOSURE                      ChannelStateChangeReasonKind = 13
	ChannelStateChangeReasonKind_CHANNEL_STATE_CHANGE_REASON_KIND_HTLCS_TIMED_OUT                            ChannelStateChangeReasonKind = 14
	ChannelStateChangeReasonKind_CHANNEL_STATE_CHANGE_REASON_KIND_PEER_FEERATE_TOO_LOW                       ChannelStateChangeReasonKind = 15
)

// Enum value maps for ChannelStateChangeReasonKind.
var (
	ChannelStateChangeReasonKind_name = map[int32]string{
		0:  "CHANNEL_STATE_CHANGE_REASON_KIND_UNSPECIFIED",
		1:  "CHANNEL_STATE_CHANGE_REASON_KIND_COUNTERPARTY_FORCE_CLOSED",
		2:  "CHANNEL_STATE_CHANGE_REASON_KIND_HOLDER_FORCE_CLOSED",
		3:  "CHANNEL_STATE_CHANGE_REASON_KIND_LEGACY_COOPERATIVE_CLOSURE",
		4:  "CHANNEL_STATE_CHANGE_REASON_KIND_COUNTERPARTY_INITIATED_COOPERATIVE_CLOSURE",
		5:  "CHANNEL_STATE_CHANGE_REASON_KIND_LOCALLY_INITIATED_COOPERATIVE_CLOSURE",
		6:  "CHANNEL_STATE_CHANGE_REASON_KIND_COMMITMENT_TX_CONFIRMED",
		7:  "CHANNEL_STATE_CHANGE_REASON_KIND_FUNDING_TIMED_OUT",
		8:  "CHANNEL_STATE_CHANGE_REASON_KIND_PROCESSING_ERROR",
		9:  "CHANNEL_STATE_CHANGE_REASON_KIND_DISCONNECTED_PEER",
		10: "CHANNEL_STATE_CHANGE_REASON_KIND_OUTDATED_CHANNEL_MANAGER",
		11: "CHANNEL_STATE_CHANGE_REASON_KIND_COUNTERPARTY_COOP_CLOSED_UNFUNDED_CHANNEL",
		12: "CHANNEL_STATE_CHANGE_REASON_KIND_LOCALLY_COOP_CLOSED_UNFUNDED_CHANNEL",
		13: "CHANNEL_STATE_CHANGE_REASON_KIND_FUNDING_BATCH_CLOSURE",
		14: "CHANNEL_STATE_CHANGE_REASON_KIND_HTLCS_TIMED_OUT",
		15: "CHANNEL_STATE_CHANGE_REASON_KIND_PEER_FEERATE_TOO_LOW",
	}
	ChannelStateChangeReasonKind_value = map[string]int32{
		"CHANNEL_STATE_CHANGE_REASON_KIND_UNSPECIFIED":                                0,
		"CHANNEL_STATE_CHANGE_REASON_KIND_COUNTERPARTY_FORCE_CLOSED":                  1,
		"CHANNEL_STATE_CHANGE_REASON_KIND_HOLDER_FORCE_CLOSED":                        2,
		"CHANNEL_STATE_CHANGE_REASON_KIND_LEGACY_COOPERATIVE_CLOSURE":                 3,
		"CHANNEL_STATE_CHANGE_REASON_KIND_COUNTERPARTY_INITIATED_COOPERATIVE_CLOSURE": 4,
		"CHANNEL_STATE_CHANGE_REASON_KIND_LOCALLY_INITIATED_COOPERATIVE_CLOSURE":      5,
		"CHANNEL_STATE_CHANGE_REASON_KIND_COMMITMENT_TX_CONFIRMED":                    6,
		"CHANNEL_STATE_CHANGE_REASON_KIND_FUNDING_TIMED_OUT":                          7,
		"CHANNEL_STATE_CHANGE_REASON_KIND_PROCESSING_ERROR":                           8,
		"CHANNEL_STATE_CHANGE_REASON_KIND_DISCONNECTED_PEER":                          9,
		"CHANNEL_STATE_CHANGE_REASON_KIND_OUTDATED_CHANNEL_MANAGER":                   10,
		"CHANNEL_STATE_CHANGE_REASON_KIND_COUNTERPARTY_COOP_CLOSED_UNFUNDED_CHANNEL":  11,
		"CHANNEL_STATE_CHANGE_REASON_KIND_LOCALLY_COOP_CLOSED_UNFUNDED_CHANNEL":       12,
		"CHANNEL_STATE_CHANGE_REASON_KIND_FUNDING_BATCH_CLOSURE":                      13,
		"CHANNEL_STATE_CHANGE_REASON_KIND_HTLCS_TIMED_OUT":                            14,
		"CHANNEL_STATE_CHANGE_REASON_KIND_PEER_FEERATE_TOO_LOW":                       15,
	}
)

func (x ChannelStateChangeReasonKind) Enum() *ChannelStateChangeReasonKind {
	p := new(ChannelStateChangeReasonKind)
	*p = x
	return p
}

func (x ChannelStateChangeReasonKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChannelStateChangeReasonKind) Descriptor() protoreflect.EnumDescriptor {
	return file_events_proto_enumTypes[2].Descriptor()
}

func (ChannelStateChangeReasonKind) Type() protoreflect.EnumType {
	return &file_events_proto_enumTypes[2]
}

func (x ChannelStateChangeReasonKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChannelStateChangeReasonKind.Descriptor instead.
func (ChannelStateChangeReasonKind) EnumDescriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{2}
}

// EventEnvelope wraps different event types in a single message to be used by EventPublisher.
type EventEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*EventEnvelope_PaymentReceived
	//	*EventEnvelope_PaymentSuccessful
	//	*EventEnvelope_PaymentFailed
	//	*EventEnvelope_PaymentForwarded
	//	*EventEnvelope_PaymentClaimable
	//	*EventEnvelope_ChannelStateChanged
	Event         isEventEnvelope_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventEnvelope) Reset() {
	*x = EventEnvelope{}
	mi := &file_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEnvelope) ProtoMessage() {}

func (x *EventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEnvelope.ProtoReflect.Descriptor instead.
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{0}
}

func (x *EventEnvelope) GetEvent() isEventEnvelope_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *EventEnvelope) GetPaymentReceived() *PaymentReceived {
	if x != nil {
		if x, ok := x.Event.(*EventEnvelope_PaymentReceived); ok {
			return x.PaymentReceived
		}
	}
	return nil
}

func (x *EventEnvelope) GetPaymentSuccessful() *PaymentSuccessful {
	if x != nil {
		if x, ok := x.Event.(*EventEnvelope_PaymentSuccessful); ok {
			return x.PaymentSuccessful
		}
	}
	return nil
}

func (x *EventEnvelope) GetPaymentFailed() *PaymentFailed {
	if x != nil {
		if x, ok := x.Event.(*EventEnvelope_PaymentFailed); ok {
			return x.PaymentFailed
		}
	}
	return nil
}

func (x *EventEnvelope) GetPaymentForwarded() *PaymentForwarded {
	if x != nil {
		if x, ok := x.Event.(*EventEnvelope_PaymentForwarded); ok {
			return x.PaymentForwarded
		}
	}
	return nil
}

func (x *EventEnvelope) GetPaymentClaimable() *PaymentClaimable {
	if x != nil {
		if x, ok := x.Event.(*EventEnvelope_PaymentClaimable); ok {
			return x.PaymentClaimable
		}
	}
	return nil
}

func (x *EventEnvelope) GetChannelStateChanged() *ChannelStateChanged {
	if x != nil {
		if x, ok := x.Event.(*EventEnvelope_ChannelStateChanged); ok {
			return x.ChannelStateChanged
		}
	}
	return nil
}

type isEventEnvelope_Event interface {
	isEventEnvelope_Event()
}

type EventEnvelope_PaymentReceived struct {
	PaymentReceived *PaymentReceived `protobuf:"bytes,2,opt,name=payment_received,json=paymentReceived,proto3,oneof"`
}

type EventEnvelope_PaymentSuccessful struct {
	PaymentSuccessful *PaymentSuccessful `protobuf:"bytes,3,opt,name=payment_successful,json=paymentSuccessful,proto3,oneof"`
}

type EventEnvelope_PaymentFailed struct {
	PaymentFailed *PaymentFailed `protobuf:"bytes,4,opt,name=payment_failed,json=paymentFailed,proto3,oneof"`
}

type EventEnvelope_PaymentForwarded struct {
	PaymentForwarded *PaymentForwarded `protobuf:"bytes,6,opt,name=payment_forwarded,json=paymentForwarded,proto3,oneof"`
}

type EventEnvelope_PaymentClaimable struct {
	PaymentClaimable *PaymentClaimable `protobuf:"bytes,7,opt,name=payment_claimable,json=paymentClaimable,proto3,oneof"`
}

type EventEnvelope_ChannelStateChanged struct {
	ChannelStateChanged *ChannelStateChanged `protobuf:"bytes,8,opt,name=channel_state_changed,json=channelStateChanged,proto3,oneof"`
}

func (*EventEnvelope_PaymentReceived) isEventEnvelope_Event() {}

func (*EventEnvelope_PaymentSuccessful) isEventEnvelope_Event() {}

func (*EventEnvelope_PaymentFailed) isEventEnvelope_Event() {}

func (*EventEnvelope_PaymentForwarded) isEventEnvelope_Event() {}

func (*EventEnvelope_PaymentClaimable) isEventEnvelope_Event() {}

func (*EventEnvelope_ChannelStateChanged) isEventEnvelope_Event() {}

type CounterpartyForceClosedDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerMsg       string                 `protobuf:"bytes,1,opt,name=peer_msg,json=peerMsg,proto3" json:"peer_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CounterpartyForceClosedDetails) Reset() {
	*x = CounterpartyForceClosedDetails{}
	mi := &file_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CounterpartyForceClosedDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CounterpartyForceClosedDetails) ProtoMessage() {}

func (x *CounterpartyForceClosedDetails) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CounterpartyForceClosedDetails.ProtoReflect.Descriptor instead.
func (*CounterpartyForceClosedDetails) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{1}
}

func (x *CounterpartyForceClosedDetails) GetPeerMsg() string {
	if x != nil {
		return x.PeerMsg
	}
	return ""
}

type HolderForceClosedDetails struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	BroadcastedLatestTxn *bool                  `protobuf:"varint,1,opt,name=broadcasted_latest_txn,json=broadcastedLatestTxn,proto3,oneof" json:"broadcasted_latest_txn,omitempty"`
	Message              string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *HolderForceClosedDetails) Reset() {
	*x = HolderForceClosedDetails{}
	mi := &file_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HolderForceClosedDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolderForceClosedDetails) ProtoMessage() {}

func (x *HolderForceClosedDetails) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HolderForceClosedDetails.ProtoReflect.Descriptor instead.
func (*HolderForceClosedDetails) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{2}
}

func (x *HolderForceClosedDetails) GetBroadcastedLatestTxn() bool {
	if x != nil && x.BroadcastedLatestTxn != nil {
		return *x.BroadcastedLatestTxn
	}
	return false
}

func (x *HolderForceClosedDetails) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ProcessingErrorDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           string                 `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessingErrorDetails) Reset() {
	*x = ProcessingErrorDetails{}
	mi := &file_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessingErrorDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessingErrorDetails) ProtoMessage() {}

func (x *ProcessingErrorDetails) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessingErrorDetails.ProtoReflect.Descriptor instead.
func (*ProcessingErrorDetails) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessingErrorDetails) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type HtlcsTimedOutDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentHash   *string                `protobuf:"bytes,1,opt,name=payment_hash,json=paymentHash,proto3,oneof" json:"payment_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HtlcsTimedOutDetails) Reset() {
	*x = HtlcsTimedOutDetails{}
	mi := &file_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HtlcsTimedOutDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HtlcsTimedOutDetails) ProtoMessage() {}

func (x *HtlcsTimedOutDetails) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HtlcsTimedOutDetails.ProtoReflect.Descriptor instead.
func (*HtlcsTimedOutDetails) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{4}
}

func (x *HtlcsTimedOutDetails) GetPaymentHash() string {
	if x != nil && x.PaymentHash != nil {
		return *x.PaymentHash
	}
	return ""
}

type PeerFeerateTooLowDetails struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	PeerFeerateSatPerKw     uint32                 `protobuf:"varint,1,opt,name=peer_feerate_sat_per_kw,json=peerFeerateSatPerKw,proto3" json:"peer_feerate_sat_per_kw,omitempty"`
	RequiredFeerateSatPerKw uint32                 `protobuf:"varint,2,opt,name=required_feerate_sat_per_kw,json=requiredFeerateSatPerKw,proto3" json:"required_feerate_sat_per_kw,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *PeerFeerateTooLowDetails) Reset() {
	*x = PeerFeerateTooLowDetails{}
	mi := &file_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerFeerateTooLowDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerFeerateTooLowDetails) ProtoMessage() {}

func (x *PeerFeerateTooLowDetails) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerFeerateTooLowDetails.ProtoReflect.Descriptor instead.
func (*PeerFeerateTooLowDetails) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{5}
}

func (x *PeerFeerateTooLowDetails) GetPeerFeerateSatPerKw() uint32 {
	if x != nil {
		return x.PeerFeerateSatPerKw
	}
	return 0
}

func (x *PeerFeerateTooLowDetails) GetRequiredFeerateSatPerKw() uint32 {
	if x != nil {
		return x.RequiredFeerateSatPerKw
	}
	return 0
}

type ChannelStateChangeReason struct {
	state   protoimpl.MessageState       `protogen:"open.v1"`
	Kind    ChannelStateChangeReasonKind `protobuf:"varint,1,opt,name=kind,proto3,enum=events.ChannelStateChangeReasonKind" json:"kind,omitempty"`
	Message string                       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Details:
	//
	//	*ChannelStateChangeReason_CounterpartyForceClosed
	//	*ChannelStateChangeReason_HolderForceClosed
	//	*ChannelStateChangeReason_ProcessingError
	//	*ChannelStateChangeReason_HtlcsTimedOut
	//	*ChannelStateChangeReason_PeerFeerateTooLow
	Details       isChannelStateChangeReason_Details `protobuf_oneof:"details"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelStateChangeReason) Reset() {
	*x = ChannelStateChangeReason{}
	mi := &file_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelStateChangeReason) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelStateChangeReason) ProtoMessage() {}

func (x *ChannelStateChangeReason) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelStateChangeReason.ProtoReflect.Descriptor instead.
func (*ChannelStateChangeReason) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{6}
}

func (x *ChannelStateChangeReason) GetKind() ChannelStateChangeReasonKind {
	if x != nil {
		return x.Kind
	}
	return ChannelStateChangeReasonKind_CHANNEL_STATE_CHANGE_REASON_KIND_UNSPECIFIED
}

func (x *ChannelStateChangeReason) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChannelStateChangeReason) GetDetails() isChannelStateChangeReason_Details {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *ChannelStateChangeReason) GetCounterpartyForceClosed() *CounterpartyForceClosedDetails {
	if x != nil {
		if x, ok := x.Details.(*ChannelStateChangeReason_CounterpartyForceClosed); ok {
			return x.CounterpartyForceClosed
		}
	}
	return nil
}

func (x *ChannelStateChangeReason) GetHolderForceClosed() *HolderForceClosedDetails {
	if x != nil {
		if x, ok := x.Details.(*ChannelStateChangeReason_HolderForceClosed); ok {
			return x.HolderForceClosed
		}
	}
	return nil
}

func (x *ChannelStateChangeReason) GetProcessingError() *ProcessingErrorDetails {
	if x != nil {
		if x, ok := x.Details.(*ChannelStateChangeReason_ProcessingError); ok {
			return x.ProcessingError
		}
	}
	return nil
}

func (x *ChannelStateChangeReason) GetHtlcsTimedOut() *HtlcsTimedOutDetails {
	if x != nil {
		if x, ok := x.Details.(*ChannelStateChangeReason_HtlcsTimedOut); ok {
			return x.HtlcsTimedOut
		}
	}
	return nil
}

func (x *ChannelStateChangeReason) GetPeerFeerateTooLow() *PeerFeerateTooLowDetails {
	if x != nil {
		if x, ok := x.Details.(*ChannelStateChangeReason_PeerFeerateTooLow); ok {
			return x.PeerFeerateTooLow
		}
	}
	return nil
}

type isChannelStateChangeReason_Details interface {
	isChannelStateChangeReason_Details()
}

type ChannelStateChangeReason_CounterpartyForceClosed struct {
	CounterpartyForceClosed *CounterpartyForceClosedDetails `protobuf:"bytes,3,opt,name=counterparty_force_closed,json=counterpartyForceClosed,proto3,oneof"`
}

type ChannelStateChangeReason_HolderForceClosed struct {
	HolderForceClosed *HolderForceClosedDetails `protobuf:"bytes,4,opt,name=holder_force_closed,json=holderForceClosed,proto3,oneof"`
}

type ChannelStateChangeReason_ProcessingError struct {
	ProcessingError *ProcessingErrorDetails `protobuf:"bytes,5,opt,name=processing_error,json=processingError,proto3,oneof"`
}

type ChannelStateChangeReason_HtlcsTimedOut struct {
	HtlcsTimedOut *HtlcsTimedOutDetails `protobuf:"bytes,6,opt,name=htlcs_timed_out,json=htlcsTimedOut,proto3,oneof"`
}

type ChannelStateChangeReason_PeerFeerateTooLow struct {
	PeerFeerateTooLow *PeerFeerateTooLowDetails `protobuf:"bytes,7,opt,name=peer_feerate_too_low,json=peerFeerateTooLow,proto3,oneof"`
}

func (*ChannelStateChangeReason_CounterpartyForceClosed) isChannelStateChangeReason_Details() {}

func (*ChannelStateChangeReason_HolderForceClosed) isChannelStateChangeReason_Details() {}

func (*ChannelStateChangeReason_ProcessingError) isChannelStateChangeReason_Details() {}

func (*ChannelStateChangeReason_HtlcsTimedOut) isChannelStateChangeReason_Details() {}

func (*ChannelStateChangeReason_PeerFeerateTooLow) isChannelStateChangeReason_Details() {}

type ChannelStateChanged struct {
	state              protoimpl.MessageState    `protogen:"open.v1"`
	ChannelId          string                    `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	UserChannelId      string                    `protobuf:"bytes,2,opt,name=user_channel_id,json=userChannelId,proto3" json:"user_channel_id,omitempty"`
	CounterpartyNodeId *string                   `protobuf:"bytes,3,opt,name=counterparty_node_id,json=counterpartyNodeId,proto3,oneof" json:"counterparty_node_id,omitempty"`
	State              ChannelState              `protobuf:"varint,4,opt,name=state,proto3,enum=events.ChannelState" json:"state,omitempty"`
	FundingTxo         *string                   `protobuf:"bytes,5,opt,name=funding_txo,json=fundingTxo,proto3,oneof" json:"funding_txo,omitempty"`
	Reason             *ChannelStateChangeReason `protobuf:"bytes,6,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	ClosureInitiator   ChannelClosureInitiator   `protobuf:"varint,7,opt,name=closure_initiator,json=closureInitiator,proto3,enum=events.ChannelClosureInitiator" json:"closure_initiator,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ChannelStateChanged) Reset() {
	*x = ChannelStateChanged{}
	mi := &file_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelStateChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelStateChanged) ProtoMessage() {}

func (x *ChannelStateChanged) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelStateChanged.ProtoReflect.Descriptor instead.
func (*ChannelStateChanged) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{7}
}

func (x *ChannelStateChanged) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ChannelStateChanged) GetUserChannelId() string {
	if x != nil {
		return x.UserChannelId
	}
	return ""
}

func (x *ChannelStateChanged) GetCounterpartyNodeId() string {
	if x != nil && x.CounterpartyNodeId != nil {
		return *x.CounterpartyNodeId
	}
	return ""
}

func (x *ChannelStateChanged) GetState() ChannelState {
	if x != nil {
		return x.State
	}
	return ChannelState_CHANNEL_STATE_UNSPECIFIED
}

func (x *ChannelStateChanged) GetFundingTxo() string {
	if x != nil && x.FundingTxo != nil {
		return *x.FundingTxo
	}
	return ""
}

func (x *ChannelStateChanged) GetReason() *ChannelStateChangeReason {
	if x != nil {
		return x.Reason
	}
	return nil
}

func (x *ChannelStateChanged) GetClosureInitiator() ChannelClosureInitiator {
	if x != nil {
		return x.ClosureInitiator
	}
	return ChannelClosureInitiator_CHANNEL_CLOSURE_INITIATOR_UNSPECIFIED
}

// PaymentReceived indicates a payment has been received.
type PaymentReceived struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The payment details for the payment in event.
	Payment *types.Payment `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	// Custom TLV records attached to the incoming payment, if any.
	CustomRecords []*types.CustomTlvRecord `protobuf:"bytes,2,rep,name=custom_records,json=customRecords,proto3" json:"custom_records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentReceived) Reset() {
	*x = PaymentReceived{}
	mi := &file_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentReceived) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentReceived) ProtoMessage() {}

func (x *PaymentReceived) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentReceived.ProtoReflect.Descriptor instead.
func (*PaymentReceived) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{8}
}

func (x *PaymentReceived) GetPayment() *types.Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

func (x *PaymentReceived) GetCustomRecords() []*types.CustomTlvRecord {
	if x != nil {
		return x.CustomRecords
	}
	return nil
}

// PaymentSuccessful indicates a sent payment was successful.
type PaymentSuccessful struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The payment details for the payment in event.
	Payment       *types.Payment `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentSuccessful) Reset() {
	*x = PaymentSuccessful{}
	mi := &file_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentSuccessful) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentSuccessful) ProtoMessage() {}

func (x *PaymentSuccessful) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentSuccessful.ProtoReflect.Descriptor instead.
func (*PaymentSuccessful) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{9}
}

func (x *PaymentSuccessful) GetPayment() *types.Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

// PaymentFailed indicates a sent payment has failed.
type PaymentFailed struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The payment details for the payment in event.
	Payment       *types.Payment `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentFailed) Reset() {
	*x = PaymentFailed{}
	mi := &file_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentFailed) ProtoMessage() {}

func (x *PaymentFailed) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentFailed.ProtoReflect.Descriptor instead.
func (*PaymentFailed) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{10}
}

func (x *PaymentFailed) GetPayment() *types.Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

// PaymentClaimable indicates a payment has arrived and is waiting to be manually claimed or failed.
// This event is only emitted for payments created via `Bolt11ReceiveForHash`.
type PaymentClaimable struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The payment details for the claimable payment.
	Payment *types.Payment `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	// Custom TLV records attached to the claimable payment, if any.
	CustomRecords []*types.CustomTlvRecord `protobuf:"bytes,2,rep,name=custom_records,json=customRecords,proto3" json:"custom_records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentClaimable) Reset() {
	*x = PaymentClaimable{}
	mi := &file_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentClaimable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentClaimable) ProtoMessage() {}

func (x *PaymentClaimable) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentClaimable.ProtoReflect.Descriptor instead.
func (*PaymentClaimable) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{11}
}

func (x *PaymentClaimable) GetPayment() *types.Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

func (x *PaymentClaimable) GetCustomRecords() []*types.CustomTlvRecord {
	if x != nil {
		return x.CustomRecords
	}
	return nil
}

// PaymentForwarded indicates a payment was forwarded through the node.
type PaymentForwarded struct {
	state            protoimpl.MessageState  `protogen:"open.v1"`
	ForwardedPayment *types.ForwardedPayment `protobuf:"bytes,1,opt,name=forwarded_payment,json=forwardedPayment,proto3" json:"forwarded_payment,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PaymentForwarded) Reset() {
	*x = PaymentForwarded{}
	mi := &file_events_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentForwarded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentForwarded) ProtoMessage() {}

func (x *PaymentForwarded) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentForwarded.ProtoReflect.Descriptor instead.
func (*PaymentForwarded) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{12}
}

func (x *PaymentForwarded) GetForwardedPayment() *types.ForwardedPayment {
	if x != nil {
		return x.ForwardedPayment
	}
	return nil
}

var File_events_proto protoreflect.FileDescriptor

const file_events_proto_rawDesc = "" +
	"\n" +
	"\fevents.proto\x12\x06events\x1a\vtypes.proto\"\xcf\x03\n" +
	"\rEventEnvelope\x12D\n" +
	"\x10payment_received\x18\x02 \x01(\v2\x17.events.PaymentReceivedH\x00R\x0fpaymentReceived\x12J\n" +
	"\x12payment_successful\x18\x03 \x01(\v2\x19.events.PaymentSuccessfulH\x00R\x11paymentSuccessful\x12>\n" +
	"\x0epayment_failed\x18\x04 \x01(\v2\x15.events.PaymentFailedH\x00R\rpaymentFailed\x12G\n" +
	"\x11payment_forwarded\x18\x06 \x01(\v2\x18.events.PaymentForwardedH\x00R\x10paymentForwarded\x12G\n" +
	"\x11payment_claimable\x18\a \x01(\v2\x18.events.PaymentClaimableH\x00R\x10paymentClaimable\x12Q\n" +
	"\x15channel_state_changed\x18\b \x01(\v2\x1b.events.ChannelStateChangedH\x00R\x13channelStateChangedB\a\n" +
	"\x05event\";\n" +
	"\x1eCounterpartyForceClosedDetails\x12\x19\n" +
	"\bpeer_msg\x18\x01 \x01(\tR\apeerMsg\"\x8a\x01\n" +
	"\x18HolderForceClosedDetails\x129\n" +
	"\x16broadcasted_latest_txn\x18\x01 \x01(\bH\x00R\x14broadcastedLatestTxn\x88\x01\x01\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageB\x19\n" +
	"\x17_broadcasted_latest_txn\"*\n" +
	"\x16ProcessingErrorDetails\x12\x10\n" +
	"\x03err\x18\x01 \x01(\tR\x03err\"O\n" +
	"\x14HtlcsTimedOutDetails\x12&\n" +
	"\fpayment_hash\x18\x01 \x01(\tH\x00R\vpaymentHash\x88\x01\x01B\x0f\n" +
	"\r_payment_hash\"\x8e\x01\n" +
	"\x18PeerFeerateTooLowDetails\x124\n" +
	"\x17peer_feerate_sat_per_kw\x18\x01 \x01(\rR\x13peerFeerateSatPerKw\x12<\n" +
	"\x1brequired_feerate_sat_per_kw\x18\x02 \x01(\rR\x17requiredFeerateSatPerKw\"\x9d\x04\n" +
	"\x18ChannelStateChangeReason\x128\n" +
	"\x04kind\x18\x01 \x01(\x0e2$.events.ChannelStateChangeReasonKindR\x04kind\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12d\n" +
	"\x19counterparty_force_closed\x18\x03 \x01(\v2&.events.CounterpartyForceClosedDetailsH\x00R\x17counterpartyForceClosed\x12R\n" +
	"\x13holder_force_closed\x18\x04 \x01(\v2 .events.HolderForceClosedDetailsH\x00R\x11holderForceClosed\x12K\n" +
	"\x10processing_error\x18\x05 \x01(\v2\x1e.events.ProcessingErrorDetailsH\x00R\x0fprocessingError\x12F\n" +
	"\x0fhtlcs_timed_out\x18\x06 \x01(\v2\x1c.events.HtlcsTimedOutDetailsH\x00R\rhtlcsTimedOut\x12S\n" +
	"\x14peer_feerate_too_low\x18\a \x01(\v2 .events.PeerFeerateTooLowDetailsH\x00R\x11peerFeerateTooLowB\t\n" +
	"\adetails\"\xa6\x03\n" +
	"\x13ChannelStateChanged\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12&\n" +
	"\x0fuser_channel_id\x18\x02 \x01(\tR\ruserChannelId\x125\n" +
	"\x14counterparty_node_id\x18\x03 \x01(\tH\x00R\x12counterpartyNodeId\x88\x01\x01\x12*\n" +
	"\x05state\x18\x04 \x01(\x0e2\x14.events.ChannelStateR\x05state\x12$\n" +
	"\vfunding_txo\x18\x05 \x01(\tH\x01R\n" +
	"fundingTxo\x88\x01\x01\x12=\n" +
	"\x06reason\x18\x06 \x01(\v2 .events.ChannelStateChangeReasonH\x02R\x06reason\x88\x01\x01\x12L\n" +
	"\x11closure_initiator\x18\a \x01(\x0e2\x1f.events.ChannelClosureInitiatorR\x10closureInitiatorB\x17\n" +
	"\x15_counterparty_node_idB\x0e\n" +
	"\f_funding_txoB\t\n" +
	"\a_reason\"z\n" +
	"\x0fPaymentReceived\x12(\n" +
	"\apayment\x18\x01 \x01(\v2\x0e.types.PaymentR\apayment\x12=\n" +
	"\x0ecustom_records\x18\x02 \x03(\v2\x16.types.CustomTlvRecordR\rcustomRecords\"=\n" +
	"\x11PaymentSuccessful\x12(\n" +
	"\apayment\x18\x01 \x01(\v2\x0e.types.PaymentR\apayment\"9\n" +
	"\rPaymentFailed\x12(\n" +
	"\apayment\x18\x01 \x01(\v2\x0e.types.PaymentR\apayment\"{\n" +
	"\x10PaymentClaimable\x12(\n" +
	"\apayment\x18\x01 \x01(\v2\x0e.types.PaymentR\apayment\x12=\n" +
	"\x0ecustom_records\x18\x02 \x03(\v2\x16.types.CustomTlvRecordR\rcustomRecords\"X\n" +
	"\x10PaymentForwarded\x12D\n" +
	"\x11forwarded_payment\x18\x01 \x01(\v2\x17.types.ForwardedPaymentR\x10forwardedPayment*\x9a\x01\n" +
	"\fChannelState\x12\x1d\n" +
	"\x19CHANNEL_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15CHANNEL_STATE_PENDING\x10\x01\x12\x17\n" +
	"\x13CHANNEL_STATE_READY\x10\x02\x12\x1d\n" +
	"\x19CHANNEL_STATE_OPEN_FAILED\x10\x03\x12\x18\n" +
	"\x14CHANNEL_STATE_CLOSED\x10\x04*\xb6\x01\n" +
	"\x17ChannelClosureInitiator\x12)\n" +
	"%CHANNEL_CLOSURE_INITIATOR_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fCHANNEL_CLOSURE_INITIATOR_LOCAL\x10\x01\x12$\n" +
	" CHANNEL_CLOSURE_INITIATOR_REMOTE\x10\x02\x12%\n" +
	"!CHANNEL_CLOSURE_INITIATOR_UNKNOWN\x10\x03*\x94\b\n" +
	"\x1cChannelStateChangeReasonKind\x120\n" +
	",CHANNEL_STATE_CHANGE_REASON_KIND_UNSPECIFIED\x10\x00\x12>\n" +
	":CHANNEL_STATE_CHANGE_REASON_KIND_COUNTERPARTY_FORCE_CLOSED\x10\x01\x128\n" +
	"4CHANNEL_STATE_CHANGE_REASON_KIND_HOLDER_FORCE_CLOSED\x10\x02\x12?\n" +
	";CHANNEL_STATE_CHANGE_REASON_KIND_LEGACY_COOPERATIVE_CLOSURE\x10\x03\x12O\n" +
	"KCHANNEL_STATE_CHANGE_REASON_KIND_COUNTERPARTY_INITIATED_COOPERATIVE_CLOSURE\x10\x04\x12J\n" +
	"FCHANNEL_STATE_CHANGE_REASON_KIND_LOCALLY_INITIATED_COOPERATIVE_CLOSURE\x10\x05\x12<\n" +
	"8CHANNEL_STATE_CHANGE_REASON_KIND_COMMITMENT_TX_CONFIRMED\x10\x06\x126\n" +
	"2CHANNEL_STATE_CHANGE_REASON_KIND_FUNDING_TIMED_OUT\x10\a\x125\n" +
	"1CHANNEL_STATE_CHANGE_REASON_KIND_PROCESSING_ERROR\x10\b\x126\n" +
	"2CHANNEL_STATE_CHANGE_REASON_KIND_DISCONNECTED_PEER\x10\t\x12=\n" +
	"9CHANNEL_STATE_CHANGE_REASON_KIND_OUTDATED_CHANNEL_MANAGER\x10\n" +
	"\x12N\n" +
	"JCHANNEL_STATE_CHANGE_REASON_KIND_COUNTERPARTY_COOP_CLOSED_UNFUNDED_CHANNEL\x10\v\x12I\n" +
	"ECHANNEL_STATE_CHANGE_REASON_KIND_LOCALLY_COOP_CLOSED_UNFUNDED_CHANNEL\x10\f\x12:\n" +
	"6CHANNEL_STATE_CHANGE_REASON_KIND_FUNDING_BATCH_CLOSURE\x10\r\x124\n" +
	"0CHANNEL_STATE_CHANGE_REASON_KIND_HTLCS_TIMED_OUT\x10\x0e\x129\n" +
	"5CHANNEL_STATE_CHANGE_REASON_KIND_PEER_FEERATE_TOO_LOW\x10\x0fb\x06proto3"

var (
	file_events_proto_rawDescOnce sync.Once
	file_events_proto_rawDescData []byte
)

func file_events_proto_rawDescGZIP() []byte {
	file_events_proto_rawDescOnce.Do(func() {
		file_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)))
	})
	return file_events_proto_rawDescData
}

var file_events_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_events_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_events_proto_goTypes = []any{
	(ChannelState)(0),                      // 0: events.ChannelState
	(ChannelClosureInitiator)(0),           // 1: events.ChannelClosureInitiator
	(ChannelStateChangeReasonKind)(0),      // 2: events.ChannelStateChangeReasonKind
	(*EventEnvelope)(nil),                  // 3: events.EventEnvelope
	(*CounterpartyForceClosedDetails)(nil), // 4: events.CounterpartyForceClosedDetails
	(*HolderForceClosedDetails)(nil),       // 5: events.HolderForceClosedDetails
	(*ProcessingErrorDetails)(nil),         // 6: events.ProcessingErrorDetails
	(*HtlcsTimedOutDetails)(nil),           // 7: events.HtlcsTimedOutDetails
	(*PeerFeerateTooLowDetails)(nil),       // 8: events.PeerFeerateTooLowDetails
	(*ChannelStateChangeReason)(nil),       // 9: events.ChannelStateChangeReason
	(*ChannelStateChanged)(nil),            // 10: events.ChannelStateChanged
	(*PaymentReceived)(nil),                // 11: events.PaymentReceived
	(*PaymentSuccessful)(nil),              // 12: events.PaymentSuccessful
	(*PaymentFailed)(nil),                  // 13: events.PaymentFailed
	(*PaymentClaimable)(nil),               // 14: events.PaymentClaimable
	(*PaymentForwarded)(nil),               // 15: events.PaymentForwarded
	(*types.Payment)(nil),                  // 16: types.Payment
	(*types.CustomTlvRecord)(nil),          // 17: types.CustomTlvRecord
	(*types.ForwardedPayment)(nil),         // 18: types.ForwardedPayment
}
var file_events_proto_depIdxs = []int32{
	11, // 0: events.EventEnvelope.payment_received:type_name -> events.PaymentReceived
	12, // 1: events.EventEnvelope.payment_successful:type_name -> events.PaymentSuccessful
	13, // 2: events.EventEnvelope.payment_failed:type_name -> events.PaymentFailed
	15, // 3: events.EventEnvelope.payment_forwarded:type_name -> events.PaymentForwarded
	14, // 4: events.EventEnvelope.payment_claimable:type_name -> events.PaymentClaimable
	10, // 5: events.EventEnvelope.channel_state_changed:type_name -> events.ChannelStateChanged
	2,  // 6: events.ChannelStateChangeReason.kind:type_name -> events.ChannelStateChangeReasonKind
	4,  // 7: events.ChannelStateChangeReason.counterparty_force_closed:type_name -> events.CounterpartyForceClosedDetails
	5,  // 8: events.ChannelStateChangeReason.holder_force_closed:type_name -> events.HolderForceClosedDetails
	6,  // 9: events.ChannelStateChangeReason.processing_error:type_name -> events.ProcessingErrorDetails
	7,  // 10: events.ChannelStateChangeReason.htlcs_timed_out:type_name -> events.HtlcsTimedOutDetails
	8,  // 11: events.ChannelStateChangeReason.peer_feerate_too_low:type_name -> events.PeerFeerateTooLowDetails
	0,  // 12: events.ChannelStateChanged.state:type_name -> events.ChannelState
	9,  // 13: events.ChannelStateChanged.reason:type_name -> events.ChannelStateChangeReason
	1,  // 14: events.ChannelStateChanged.closure_initiator:type_name -> events.ChannelClosureInitiator
	16, // 15: events.PaymentReceived.payment:type_name -> types.Payment
	17, // 16: events.PaymentReceived.custom_records:type_name -> types.CustomTlvRecord
	16, // 17: events.PaymentSuccessful.payment:type_name -> types.Payment
	16, // 18: events.PaymentFailed.payment:type_name -> types.Payment
	16, // 19: events.PaymentClaimable.payment:type_name -> types.Payment
	17, // 20: events.PaymentClaimable.custom_records:type_name -> types.CustomTlvRecord
	18, // 21: events.PaymentForwarded.forwarded_payment:type_name -> types.ForwardedPayment
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_events_proto_init() }
func file_events_proto_init() {
	if File_events_proto != nil {
		return
	}
	file_events_proto_msgTypes[0].OneofWrappers = []any{
		(*EventEnvelope_PaymentReceived)(nil),
		(*EventEnvelope_PaymentSuccessful)(nil),
		(*EventEnvelope_PaymentFailed)(nil),
		(*EventEnvelope_PaymentForwarded)(nil),
		(*EventEnvelope_PaymentClaimable)(nil),
		(*EventEnvelope_ChannelStateChanged)(nil),
	}
	file_events_proto_msgTypes[2].OneofWrappers = []any{}
	file_events_proto_msgTypes[4].OneofWrappers = []any{}
	file_events_proto_msgTypes[6].OneofWrappers = []any{
		(*ChannelStateChangeReason_CounterpartyForceClosed)(nil),
		(*ChannelStateChangeReason_HolderForceClosed)(nil),
		(*ChannelStateChangeReason_ProcessingError)(nil),
		(*ChannelStateChangeReason_HtlcsTimedOut)(nil),
		(*ChannelStateChangeReason_PeerFeerateTooLow)(nil),
	}
	file_events_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_proto_goTypes,
		DependencyIndexes: file_events_proto_depIdxs,
		EnumInfos:         file_events_proto_enumTypes,
		MessageInfos:      file_events_proto_msgTypes,
	}.Build()
	File_events_proto = out.File
	file_events_proto_goTypes = nil
	file_events_proto_depIdxs = nil
}
