filename: "{{.InterfaceName}}.go"
dir: tests/mocks
pkgname: mocks
template: testify
packages:
  github.com/getAlby/hub/config:
    interfaces:
      Config: {}
  github.com/getAlby/hub/lnclient:
    interfaces:
      LNClient: {}
  github.com/getAlby/hub/service:
    interfaces:
      Service: {}
