filename: "{{.InterfaceName}}.go"
dir: tests/mocks
outpkg: mocks

# Fix deprecation warnings:
issue-845-fix: True
resolve-type-alias: False

packages:
  github.com/getAlby/hub/service:
    interfaces:
      Service:

  github.com/getAlby/hub/lnclient:
    interfaces:
      LNClient:
