services:
  - type: web
    runtime: image
    name: albyhub
    image:
      url: ghcr.io/getalby/hub:latest
    numInstances: 1
    region: frankfurt # Default: oregon
    plan: starter
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    autoDeploy: false
    envVars:
      - key: WORK_DIR
        value: /data/albyhub
      - key: LDK_ESPLORA_SERVER
        value: "https://electrs.getalbypro.com"
