CREATE TABLE `apps` (`id` integer,`name` text,`description` text,`nostr_pubkey` text UNIQUE,`created_at` datetime,`updated_at` datetime,PRIMARY KEY (`id`));
CREATE TABLE `app_permissions` (`id` integer,`app_id` integer,`request_method` text,`max_amount` integer,`budget_renewal` text,`expires_at` datetime,`created_at` datetime,`updated_at` datetime,PRIMARY KEY (`id`),CONSTRAINT `fk_app_permissions_app` FOREIGN KEY (`app_id`) REFERENCES `apps`(`id`) ON DELETE CASCADE);
CREATE INDEX `idx_app_permissions_request_method` ON `app_permissions`(`request_method`);
CREATE INDEX `idx_app_permissions_app_id` ON `app_permissions`(`app_id`);
CREATE TABLE `payments` (`id` integer,`app_id` integer,`nostr_event_id` integer,`amount` integer,`payment_request` text,`preimage` text,`created_at` datetime,`updated_at` datetime, `preimage2` text,PRIMARY KEY (`id`),CONSTRAINT `fk_payments_app` FOREIGN KEY (`app_id`) REFERENCES `apps`(`id`) ON DELETE CASCADE,CONSTRAINT `fk_payments_nostr_event` FOREIGN KEY (`nostr_event_id`) REFERENCES `nostr_events`(`id`));
CREATE INDEX `idx_payments_nostr_event_id` ON `payments`(`nostr_event_id`);
CREATE INDEX `idx_payments_app_id` ON `payments`(`app_id`);
CREATE TABLE "nostr_events" (`id` integer,`app_id` integer,`nostr_id` text UNIQUE,`reply_id` text,`content` text,`state` text,`replied_at` datetime,`created_at` datetime,`updated_at` datetime,PRIMARY KEY (`id`),CONSTRAINT `fk_nostr_events_app` FOREIGN KEY (`app_id`) REFERENCES `apps`(`id`) ON DELETE CASCADE);
CREATE UNIQUE INDEX `idx_nostr_events_nostr_id` ON `nostr_events`(`nostr_id`);
CREATE INDEX `idx_nostr_events_app_id` ON `nostr_events`(`app_id`);
CREATE INDEX idx_payment_sum ON payments (app_id, preimage, created_at);
CREATE INDEX idx_nostr_events_app_id_and_id ON nostr_events(app_id, id);
CREATE TABLE configs (id int NOT NULL PRIMARY KEY, ln_backend_type TEXT, lnd_address TEXT, lnd_cert_hex TEXT, lnd_macaroon_hex TEXT, breez_api_key TEXT, breez_mnemonic TEXT, greenlight_invite_code TEXT, nostr_secret_key TEXT, created_at datetime, updated_at datetime);