name: Release

on:
  workflow_dispatch:

jobs:
  build-server:
    uses: ./.github/workflows/http.yml

  build-wails:
    uses: ./.github/workflows/wails.yml
    with:
      build-release: true
    secrets:
      APPLE_DEVELOPER_CERTIFICATE_P12_BASE64: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_P12_BASE64 }}
      APPLE_DEVELOPER_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_PASSWORD }}
      APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      APPLE_USERNAME: ${{ secrets.APPLE_USERNAME }}

  release-draft:
    needs:
      - build-server
      - build-wails
    uses: ./.github/workflows/create-release.yaml
    secrets:
      repo-token: ${{ secrets.GITHUB_TOKEN }}
